name: ivent_trial
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Core
  get: ^4.7.2

  # UI
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFProFonts/SF-Pro-Display-Black.otf
          weight: 900
        - asset: assets/fonts/SFProFonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/SFProFonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SFProFonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SFProFonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SFProFonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SFProFonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SFProFonts/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: assets/fonts/SFProFonts/SF-Pro-Display-Ultralight.otf
          weight: 100
        
        
        
    
