const hobbies = {
  "Sanat & Kültür": [
    "Tiyatro",
    "Opera",
    "Bale",
    "Resim",
    "Heykel",
    "Mimarlık",
    "Fotoğrafçılık",
    "Sinema",
    "Edebiyat",
    "Şiir",
    "Karikatür",
    "Halk Dansları",
    "Modern Dans",
    "Grafik Tasarım",
    "Moda",
    "Seramik",
    "Kaligrafi",
    "Geleneksel El Sanatları",
    "Müze & Sergiler",
    "Felsefe",
  ],
  "Müzik": [
    "Rock",
    "Pop",
    "Caz",
    "Blues",
    "Klasik Müzik",
    "Hip-Hop",
    "Rap",
    "Elektronik",
    "House",
    "Techno",
    "Metal",
    "Punk",
    "Reggae",
    "Folk",
    "Türk Halk Müziği",
    "Türk Sanat Müziği",
    "R&B",
    "Soul",
    "Lo-Fi",
    "Indie",
  ],
  "Spor": [
    "Futbol",
    "Basketbol",
    "Voleybol",
    "Tenis",
    "Masa Tenisi",
    "Yüzme",
    "Atletizm",
    "Bisiklet",
    "Boks",
    "Kickboks",
    "Karate",
    "Judo",
    "Taekwondo",
    "Güreş",
    "Halter",
    "Jimnastik",
    "Kayak",
    "Snowboard",
    "Okçuluk",
    "E-Spor",
  ],
};
